/* Data + translations for Bitki Hub.
   No JSX here, just constants attached to window. */

const UNSPLASH = (id, w = 900) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=70`;

const CATEGORIES = [
  { id: "trees",     en: "Ornamental Trees",     ar: "أشجار الزينة",
    blurb: { en: "Established specimens for streets, plazas and estates.", ar: "أشجار راسخة للشوارع والساحات والممتلكات." },
    img: UNSPLASH("photo-1542273917363-3b1817f69a2d", 900) },
  { id: "palms",     en: "Palms",                ar: "النخيل",
    blurb: { en: "Field-grown date and fan palms acclimated to Gulf summers.", ar: "نخيل حقلي مهيأ لمناخ الخليج." },
    img: UNSPLASH("photo-1503614472-8c93d56e92ce", 900) },
  { id: "hedges",    en: "Hedges & Screening",   ar: "أسوار وحواجز نباتية",
    blurb: { en: "Privacy and wind-break species in nursery-grown rows.", ar: "نباتات الخصوصية ومصدات الرياح." },
    img: UNSPLASH("photo-1466692476868-aef1dfb1e735", 900) },
  { id: "indoor",    en: "Indoor Decorative",    ar: "نباتات داخلية",
    blurb: { en: "Interior species for hotels, offices and showrooms.", ar: "نباتات داخلية للفنادق والمكاتب." },
    img: UNSPLASH("photo-1485955900006-10f4d324d411", 900) },
  { id: "ground",    en: "Ground Cover",         ar: "نباتات الغطاء الأرضي",
    blurb: { en: "Low-water spreaders and turf alternatives.", ar: "نباتات منخفضة استهلاك المياه." },
    img: UNSPLASH("photo-1416879595882-3373a0480b5b", 900) },
  { id: "succulents",en: "Succulents & Cacti",   ar: "نباتات عصارية وصبار",
    blurb: { en: "Drought-tolerant sculptural pieces.", ar: "قطع نحتية مقاومة للجفاف." },
    img: UNSPLASH("photo-1459411552884-841db9b3cc2a", 900) },
];

const PRODUCTS = [
  {
    id: "olea-europaea-150",
    name: { en: "Mediterranean Olive", ar: "زيتون متوسطي" },
    latin: "Olea europaea",
    cat: "trees",
    badge: { en: "Best seller", ar: "الأكثر طلباً" },
    price: 145, unit: "USD",
    moq: 50,
    height: "150–180 cm",
    pot: "30 L",
    climate: "Arid · Mediterranean",
    water: "Low",
    sun: "Full sun",
    age: "8 years",
    img: UNSPLASH("photo-1568084680786-a84f91d1153c", 900),
    gallery: [
      "photo-1568084680786-a84f91d1153c",
      "photo-1542273917363-3b1817f69a2d",
      "photo-1500354960849-9c3d50dee9c8",
      "photo-1485955900006-10f4d324d411",
    ].map(id => UNSPLASH(id)),
    desc: {
      en: "Field-grown Olea europaea trained for landscape installation. Hardened off through two full summer cycles in Yalova, ready for road haul to the Gulf and Levant.",
      ar: "زيتون أوروبي مزروع في الحقل ومُهيأ للتثبيت في المشاريع الكبرى."
    }
  },
  {
    id: "phoenix-dact-2m",
    name: { en: "Date Palm", ar: "نخلة التمر" },
    latin: "Phoenix dactylifera",
    cat: "palms",
    badge: null,
    price: 280, unit: "USD",
    moq: 25,
    height: "2.0–2.5 m",
    pot: "Field-grown",
    climate: "Hot · Arid",
    water: "Moderate",
    sun: "Full sun",
    age: "6 years",
    img: UNSPLASH("photo-1503614472-8c93d56e92ce", 900),
    gallery: ["photo-1503614472-8c93d56e92ce","photo-1469474968028-56623f02e42e","photo-1542273917363-3b1817f69a2d","photo-1416879595882-3373a0480b5b"].map(id=>UNSPLASH(id)),
    desc: {
      en: "Mature Phoenix dactylifera ready for resort and avenue planting. Inspected for red palm weevil and certified phytosanitary clean.",
      ar: "نخلة تمر ناضجة معتمدة صحياً." }
  },
  {
    id: "washingtonia-3m",
    name: { en: "Mexican Fan Palm", ar: "نخلة واشنطن" },
    latin: "Washingtonia robusta",
    cat: "palms",
    badge: { en: "New stock", ar: "وارد جديد" },
    price: 420, unit: "USD",
    moq: 20,
    height: "3.0–3.5 m",
    pot: "Root-balled",
    climate: "Hot · Arid",
    water: "Low",
    sun: "Full sun",
    age: "9 years",
    img: UNSPLASH("photo-1469474968028-56623f02e42e", 900),
    gallery: ["photo-1469474968028-56623f02e42e","photo-1503614472-8c93d56e92ce","photo-1466692476868-aef1dfb1e735","photo-1542273917363-3b1817f69a2d"].map(id=>UNSPLASH(id)),
    desc: {
      en: "Tall fan palms for boulevards and gated communities. Trunk cleaned and ready for crane lift.",
      ar: "نخيل مروحي طويل للجادات." }
  },
  {
    id: "cupressus-180",
    name: { en: "Italian Cypress", ar: "السرو الإيطالي" },
    latin: "Cupressus sempervirens",
    cat: "trees",
    badge: null,
    price: 65, unit: "USD",
    moq: 100,
    height: "180–220 cm",
    pot: "20 L",
    climate: "Mediterranean",
    water: "Low",
    sun: "Full sun",
    age: "5 years",
    img: UNSPLASH("photo-1559554498-fc54e8aae883", 900),
    gallery: ["photo-1559554498-fc54e8aae883","photo-1466692476868-aef1dfb1e735","photo-1542273917363-3b1817f69a2d","photo-1416879595882-3373a0480b5b"].map(id=>UNSPLASH(id)),
    desc: { en: "Column form, perfect for property boundaries and avenue runs.", ar: "شكل عمودي مثالي للحدود." }
  },
  {
    id: "ficus-lyrata",
    name: { en: "Fiddle-Leaf Fig", ar: "تين الكمان" },
    latin: "Ficus lyrata",
    cat: "indoor",
    badge: { en: "Hotel grade", ar: "فئة الفنادق" },
    price: 95, unit: "USD",
    moq: 30,
    height: "160–200 cm",
    pot: "22 L decorative",
    climate: "Interior",
    water: "Moderate",
    sun: "Bright indirect",
    age: "3 years",
    img: UNSPLASH("photo-1485955900006-10f4d324d411", 900),
    gallery: ["photo-1485955900006-10f4d324d411","photo-1614594975525-e45190c55d0b","photo-1459411552884-841db9b3cc2a","photo-1416879595882-3373a0480b5b"].map(id=>UNSPLASH(id)),
    desc: { en: "Tall, single-leader fiddle-leafs trained for lobby and showroom placement.", ar: "نباتات داخلية طويلة للفنادق." }
  },
  {
    id: "monstera-deliciosa",
    name: { en: "Swiss Cheese Plant", ar: "مونستيرا" },
    latin: "Monstera deliciosa",
    cat: "indoor",
    badge: null,
    price: 38, unit: "USD",
    moq: 50,
    height: "80–110 cm",
    pot: "12 L",
    climate: "Interior",
    water: "Moderate",
    sun: "Bright indirect",
    age: "2 years",
    img: UNSPLASH("photo-1614594975525-e45190c55d0b", 900),
    gallery: ["photo-1614594975525-e45190c55d0b","photo-1485955900006-10f4d324d411","photo-1416879595882-3373a0480b5b","photo-1459411552884-841db9b3cc2a"].map(id=>UNSPLASH(id)),
    desc: { en: "Mature, multi-stem Monsteras for interior landscaping.", ar: "نباتات داخلية ناضجة." }
  },
  {
    id: "thuja-200",
    name: { en: "Thuja Hedge", ar: "سرو الثوجا" },
    latin: "Thuja occidentalis",
    cat: "hedges",
    badge: null,
    price: 42, unit: "USD",
    moq: 200,
    height: "180–220 cm",
    pot: "15 L",
    climate: "Temperate",
    water: "Moderate",
    sun: "Full to part sun",
    age: "4 years",
    img: UNSPLASH("photo-1466692476868-aef1dfb1e735", 900),
    gallery: ["photo-1466692476868-aef1dfb1e735","photo-1559554498-fc54e8aae883","photo-1542273917363-3b1817f69a2d","photo-1416879595882-3373a0480b5b"].map(id=>UNSPLASH(id)),
    desc: { en: "Dense evergreen hedge species for privacy walls.", ar: "أسوار خضراء كثيفة." }
  },
  {
    id: "lavender-row",
    name: { en: "English Lavender", ar: "خزامى إنجليزي" },
    latin: "Lavandula angustifolia",
    cat: "ground",
    badge: { en: "Drought-tolerant", ar: "مقاوم للجفاف" },
    price: 8, unit: "USD",
    moq: 500,
    height: "30–40 cm",
    pot: "2 L",
    climate: "Mediterranean",
    water: "Very low",
    sun: "Full sun",
    age: "1 year",
    img: UNSPLASH("photo-1499002238440-d264edd596ec", 900),
    gallery: ["photo-1499002238440-d264edd596ec","photo-1416879595882-3373a0480b5b","photo-1559554498-fc54e8aae883","photo-1542273917363-3b1817f69a2d"].map(id=>UNSPLASH(id)),
    desc: { en: "Sun-loving lavender rows for mass planting and pollinator strips.", ar: "خزامى لمصدّات الزينة." }
  },
];

const PROJECTS = [
  { id:1, title:{en:"Red Sea Resort — Avenue Planting", ar:"منتجع البحر الأحمر"}, loc:"Jeddah, KSA",
    meta:["1,400 palms","18 months","Hospitality"], img: UNSPLASH("photo-1469474968028-56623f02e42e",1200) },
  { id:2, title:{en:"Lusail Tower District", ar:"حي أبراج لوسيل"}, loc:"Doha, Qatar",
    meta:["320 specimen trees","Corporate","2024"], img: UNSPLASH("photo-1542273917363-3b1817f69a2d",1200) },
  { id:3, title:{en:"Sharq Embassy Quarter", ar:"حي السفارات"}, loc:"Kuwait City, Kuwait",
    meta:["Hedges + ground cover","Government","2023"], img: UNSPLASH("photo-1466692476868-aef1dfb1e735",1200) },
  { id:4, title:{en:"Amman Hotel Atrium", ar:"بهو فندق عمّان"}, loc:"Amman, Jordan",
    meta:["Interior specimens","Hospitality","2024"], img: UNSPLASH("photo-1485955900006-10f4d324d411",1200) },
];

const STRINGS = {
  en: {
    nav: { home: "Home", products: "Catalogue", projects: "Projects", blog: "Blog", faq: "FAQ", about: "About", contact: "Contact" },
    cta: { quote: "Request a quote", call: "Talk to a specialist", browse: "Browse catalogue", view: "View specimen", explore: "Explore" },
    heroEyebrow: "Yalova, Türkiye → MENA wholesale",
    heroTitleA: "Farming",
    heroTitleEm: "the future",
    heroTitleB: "of greener cities.",
    heroSub: "Field-grown ornamentals, palms and indoor specimens shipped from our 40-hectare nursery in Yalova to landscape contractors, developers and nurseries across the MENA region.",
    heroStat1: ["40 ha", "Production area"],
    heroStat2: ["180+", "Species in stock"],
    heroStat3: ["12", "Countries served"],
    sec1Eyebrow: "Catalogue",
    sec1Title: "A working catalogue, not a coffee-table book.",
    sec1Sub: "Every specimen is field-grown, hardened off in Yalova, and prepared for the heat that's waiting on the other end.",
    sec2Eyebrow: "Why Bitki Hub",
    sec2Title: "Built for landscape work at scale.",
    sec2Items: [
      { t:"Field-grown, not warehouse-flipped", b:"We grow what we ship. Every specimen has spent at least two full seasons in our soil." },
      { t:"Phytosanitary certified", b:"EU and GCC export documentation handled in-house, so your container clears customs on the first attempt." },
      { t:"Container-loaded in Yalova", b:"Loaded by our team, sealed at origin, and shipped by reefer to Jebel Ali, Dammam or Aqaba on a fixed weekly schedule." },
      { t:"Survival guarantee", b:"60-day replacement on certified specimens — because a dead palm on a boulevard is your problem and ours." },
    ],
    stripItems: ["Field grown in Yalova", "Phytosanitary certified", "MENA weekly shipping", "Survival guarantee", "Wholesale only"],
    statsTitle: "Numbers we plant against.",
    stats: [["40", "Hectares of production"], ["180+", "Species in active stock"], ["1.2M", "Specimens grown / year"], ["12", "Countries served"]],
    projectsEyebrow: "Projects",
    projectsTitle: "Where our trees end up.",
    projectsSub: "A small selection of recent installations across the Gulf and Levant.",
    certsEyebrow: "Certifications",
    certsTitle: "Cleared, certified, and ready to ship.",
    certs: [
      { t:"EU Plant Passport", b:"Every batch tagged and traceable." },
      { t:"GCC Phytosanitary", b:"Inspected per importing country." },
      { t:"Global GAP", b:"Good Agricultural Practices, audited." },
      { t:"ISO 9001:2015", b:"Quality management certified." },
    ],
    ctaTitle: "Tell us what you're planting and we'll quote the container.",
    ctaSub: "Average response: under 24 hours, in English or Arabic.",
    productsTitle: "The Catalogue",
    productsSub: "Filter by category, search by species, request a quote on anything in stock.",
    productsResultsFmt: (n, t) => `Showing ${n} of ${t} specimens`,
    sortLabel: "Sort:",
    sortOptions: ["Featured", "Price: low to high", "Price: high to low", "Height: tall to short", "Min order"],
    searchPlaceholder: "Search Olea, Phoenix, Ficus…",
    pdSpecsTitle: "Specifications",
    pdSpecs: { height:"Height", pot:"Container", climate:"Climate fit", water:"Water need", sun:"Light", age:"Age", moq:"Min. order", origin:"Origin" },
    pdTabs: ["Description", "Care & climate", "Shipping & lead time"],
    pdRelated: "Other specimens you may need",
    contactTitle: "Let's talk container.",
    contactLede: "Send us your project list — species, sizes, quantities, port of entry — and we'll come back with a quote, a lead time and a loading plan. Usually within a working day.",
    contactCardTitle: "Project enquiry",
    contactCardSub: "Wholesale only. For one-off plants, contact a local retailer.",
    fields: {
      name:"Full name", company:"Company", email:"Work email", phone:"Phone / WhatsApp",
      country:"Country of delivery", buyer:"You are a…",
      species:"Species & quantities", message:"Anything else we should know",
    },
    buyers: ["Landscaper", "Developer", "Nursery", "Other"],
    submit: "Send enquiry",
    submitNote: "By submitting you agree to be contacted about your enquiry. We don't sell your data.",
    successTitle: "Enquiry received.",
    successBody: "We'll come back within one working day with a quote and lead time. A copy has been sent to your email.",
    successBack: "Send another",
    footer: {
      tagline: "Field-grown ornamentals from Yalova, Türkiye — shipped wholesale to the MENA region and beyond.",
      colA: "Catalogue", colAItems: ["Ornamental trees", "Palms", "Hedges", "Indoor decorative", "Ground cover", "Succulents"],
      colB: "Company",   colBItems: ["About us", "Our nursery", "Projects", "Blog", "FAQ", "Careers"],
      colC: "Legal",     colCItems: ["Privacy policy", "Terms & conditions", "Shipping policy", "Cookie settings", "Imprint"],
      colD: "Contact",   colDItems: ["Yalova, Türkiye", "+90 226 — — —", "sales@bitkihub.com", "WhatsApp", "Instagram"],
      bottom: "© 2026 Bitki Hub. All rights reserved.",
      tagBottom: "Farming the future."
    },
    requestQuote: "Request a quote",
    addToEnquiry: "Add to enquiry",
    qtyLabel: "Quantity",
    related: "Related specimens",
    backToCatalogue: "Back to catalogue",
  },
  ar: {
    nav: { home: "الرئيسية", products: "الكتالوج", projects: "المشاريع", blog: "المدوّنة", faq: "الأسئلة", about: "من نحن", contact: "تواصل" },
    cta: { quote: "اطلب عرض سعر", call: "تحدّث مع مختص", browse: "تصفح الكتالوج", view: "تفاصيل النبات", explore: "اكتشف" },
    heroEyebrow: "يالوفا، تركيا ← الجملة في الشرق الأوسط",
    heroTitleA: "نزرع",
    heroTitleEm: "مستقبل",
    heroTitleB: "مدن أكثر اخضراراً.",
    heroSub: "نباتات الزينة والنخيل والنباتات الداخلية، نُربّيها في مشتلنا في يالوفا على مساحة 40 هكتاراً، ونصدّرها إلى مقاولي تنسيق الحدائق والمطوّرين والمشاتل في منطقة الشرق الأوسط وشمال أفريقيا.",
    heroStat1: ["40 هكتار", "مساحة الإنتاج"],
    heroStat2: ["180+", "نوع متوفر"],
    heroStat3: ["12", "دولة تصدير"],
    sec1Eyebrow: "الكتالوج",
    sec1Title: "كتالوج عملي، لا كتاب زينة.",
    sec1Sub: "كل نبات نباتنا منذ بذرته، مُهيأ لحرارة وجهته.",
    sec2Eyebrow: "لماذا Bitki Hub",
    sec2Title: "مصمَّم لمشاريع التنسيق الكبيرة.",
    sec2Items: [
      { t:"حقلي لا مستورد", b:"كل نبات قضى موسمين على الأقل في تربتنا." },
      { t:"شهادة صحية معتمدة", b:"وثائق الاتحاد الأوروبي ودول الخليج جاهزة لتخليص جمركي سلس." },
      { t:"تحميل الحاويات في يالوفا", b:"شحن بحري أسبوعي إلى جبل علي والدمام والعقبة." },
      { t:"ضمان البقاء", b:"استبدال خلال 60 يوماً للنباتات المعتمدة." },
    ],
    stripItems: ["مزروع في يالوفا", "شهادة صحية", "شحن أسبوعي", "ضمان البقاء", "بيع جملة فقط"],
    statsTitle: "أرقام نقيس بها أنفسنا.",
    stats: [["40", "هكتار إنتاج"], ["180+", "نوع متوفر"], ["1.2M", "نبتة سنوياً"], ["12", "دولة تصدير"]],
    projectsEyebrow: "المشاريع",
    projectsTitle: "أين تنتهي أشجارنا.",
    projectsSub: "مختارات من تنفيذات حديثة في الخليج وبلاد الشام.",
    certsEyebrow: "الشهادات",
    certsTitle: "معتمد، جاهز للشحن.",
    certs: [
      { t:"جواز نباتي أوروبي", b:"كل دفعة مرقّمة وقابلة للتتبع." },
      { t:"شهادة صحية خليجية", b:"فحص حسب بلد الاستيراد." },
      { t:"Global GAP", b:"ممارسات زراعية جيدة معتمدة." },
      { t:"ISO 9001:2015", b:"إدارة الجودة." },
    ],
    ctaTitle: "أخبرنا بما تزرعه، ونرسل لك عرض سعر للحاوية.",
    ctaSub: "متوسط الرد: أقل من 24 ساعة، بالعربية أو الإنجليزية.",
    productsTitle: "الكتالوج",
    productsSub: "تصفية حسب الفئة، بحث بالاسم العلمي، طلب عرض سعر.",
    productsResultsFmt: (n, t) => `عرض ${n} من ${t} نبات`,
    sortLabel: "ترتيب:",
    sortOptions: ["الأبرز", "السعر: من الأقل", "السعر: من الأعلى", "الارتفاع: من الأطول", "الحد الأدنى للطلب"],
    searchPlaceholder: "ابحث عن زيتون، نخيل، فيكس…",
    pdSpecsTitle: "المواصفات",
    pdSpecs: { height:"الارتفاع", pot:"الوعاء", climate:"المناخ", water:"احتياج الماء", sun:"الإضاءة", age:"العمر", moq:"الحد الأدنى للطلب", origin:"المنشأ" },
    pdTabs: ["الوصف", "الرعاية والمناخ", "الشحن والتنفيذ"],
    pdRelated: "نباتات أخرى قد تحتاجها",
    contactTitle: "لنتحدّث عن حاويتك.",
    contactLede: "أرسل لنا قائمة مشروعك: الأنواع، الأحجام، الكميات، وميناء الوصول — وسنرد بعرض سعر وخطة تحميل خلال يوم عمل.",
    contactCardTitle: "استفسار مشروع",
    contactCardSub: "بيع جملة فقط.",
    fields: {
      name:"الاسم الكامل", company:"الشركة", email:"البريد الإلكتروني", phone:"هاتف / واتساب",
      country:"دولة التسليم", buyer:"أنت…",
      species:"الأنواع والكميات", message:"أي ملاحظات أخرى",
    },
    buyers: ["مقاول تنسيق", "مطوّر", "مشتل", "أخرى"],
    submit: "إرسال الاستفسار",
    submitNote: "بالإرسال توافق على التواصل بشأن الاستفسار.",
    successTitle: "تم استلام الاستفسار.",
    successBody: "سنتواصل خلال يوم عمل بعرض سعر وخطة تنفيذ.",
    successBack: "إرسال آخر",
    footer: {
      tagline: "نباتات زينة حقلية من يالوفا، تركيا — شحن جملة إلى منطقة الشرق الأوسط وشمال أفريقيا.",
      colA: "الكتالوج", colAItems: ["أشجار الزينة", "النخيل", "أسوار نباتية", "نباتات داخلية", "غطاء أرضي", "عصاريات وصبار"],
      colB: "الشركة",   colBItems: ["من نحن", "المشتل", "المشاريع", "المدوّنة", "الأسئلة الشائعة", "وظائف"],
      colC: "قانوني",   colCItems: ["سياسة الخصوصية", "الشروط والأحكام", "سياسة الشحن", "إعدادات الكوكي", "بيانات النشر"],
      colD: "تواصل",    colDItems: ["يالوفا، تركيا", "+90 226 — — —", "sales@bitkihub.com", "واتساب", "انستغرام"],
      bottom: "© 2026 Bitki Hub. جميع الحقوق محفوظة.",
      tagBottom: "نزرع المستقبل."
    },
    requestQuote: "اطلب عرض سعر",
    addToEnquiry: "أضف للاستفسار",
    qtyLabel: "الكمية",
    related: "نباتات ذات صلة",
    backToCatalogue: "العودة للكتالوج",
  }
};

const COUNTRIES_EN = ["Saudi Arabia","United Arab Emirates","Qatar","Kuwait","Bahrain","Oman","Jordan","Libya","Egypt","Iraq","Lebanon","Türkiye","Other"];
const COUNTRIES_AR = ["السعودية","الإمارات","قطر","الكويت","البحرين","عُمان","الأردن","ليبيا","مصر","العراق","لبنان","تركيا","أخرى"];

/* Country dial-code library — MENA-priority, then key markets.
   In production this list will be initialised from the visitor's IP via a geo-lookup. */
const DIAL_CODES = [
  // MENA priority block
  { code: "SA", flag: "🇸🇦", dial: "+966", name: { en: "Saudi Arabia",         ar: "السعودية" } },
  { code: "AE", flag: "🇦🇪", dial: "+971", name: { en: "United Arab Emirates", ar: "الإمارات" } },
  { code: "QA", flag: "🇶🇦", dial: "+974", name: { en: "Qatar",                ar: "قطر" } },
  { code: "KW", flag: "🇰🇼", dial: "+965", name: { en: "Kuwait",               ar: "الكويت" } },
  { code: "BH", flag: "🇧🇭", dial: "+973", name: { en: "Bahrain",              ar: "البحرين" } },
  { code: "OM", flag: "🇴🇲", dial: "+968", name: { en: "Oman",                 ar: "عُمان" } },
  { code: "JO", flag: "🇯🇴", dial: "+962", name: { en: "Jordan",               ar: "الأردن" } },
  { code: "LY", flag: "🇱🇾", dial: "+218", name: { en: "Libya",                ar: "ليبيا" } },
  { code: "EG", flag: "🇪🇬", dial: "+20",  name: { en: "Egypt",                ar: "مصر" } },
  { code: "IQ", flag: "🇮🇶", dial: "+964", name: { en: "Iraq",                 ar: "العراق" } },
  { code: "LB", flag: "🇱🇧", dial: "+961", name: { en: "Lebanon",              ar: "لبنان" } },
  { code: "SY", flag: "🇸🇾", dial: "+963", name: { en: "Syria",                ar: "سوريا" } },
  { code: "YE", flag: "🇾🇪", dial: "+967", name: { en: "Yemen",                ar: "اليمن" } },
  { code: "PS", flag: "🇵🇸", dial: "+970", name: { en: "Palestine",            ar: "فلسطين" } },
  { code: "MA", flag: "🇲🇦", dial: "+212", name: { en: "Morocco",              ar: "المغرب" } },
  { code: "TN", flag: "🇹🇳", dial: "+216", name: { en: "Tunisia",              ar: "تونس" } },
  { code: "DZ", flag: "🇩🇿", dial: "+213", name: { en: "Algeria",              ar: "الجزائر" } },
  { code: "SD", flag: "🇸🇩", dial: "+249", name: { en: "Sudan",                ar: "السودان" } },
  // Origin
  { code: "TR", flag: "🇹🇷", dial: "+90",  name: { en: "Türkiye",              ar: "تركيا" } },
  // Europe
  { code: "GB", flag: "🇬🇧", dial: "+44",  name: { en: "United Kingdom",       ar: "المملكة المتحدة" } },
  { code: "DE", flag: "🇩🇪", dial: "+49",  name: { en: "Germany",              ar: "ألمانيا" } },
  { code: "FR", flag: "🇫🇷", dial: "+33",  name: { en: "France",               ar: "فرنسا" } },
  { code: "IT", flag: "🇮🇹", dial: "+39",  name: { en: "Italy",                ar: "إيطاليا" } },
  { code: "ES", flag: "🇪🇸", dial: "+34",  name: { en: "Spain",                ar: "إسبانيا" } },
  { code: "NL", flag: "🇳🇱", dial: "+31",  name: { en: "Netherlands",          ar: "هولندا" } },
  // Other major
  { code: "US", flag: "🇺🇸", dial: "+1",   name: { en: "United States",        ar: "الولايات المتحدة" } },
  { code: "CA", flag: "🇨🇦", dial: "+1",   name: { en: "Canada",               ar: "كندا" } },
  { code: "IN", flag: "🇮🇳", dial: "+91",  name: { en: "India",                ar: "الهند" } },
  { code: "PK", flag: "🇵🇰", dial: "+92",  name: { en: "Pakistan",             ar: "باكستان" } },
];

/* ============================================================
   FAQ — common B2B trade-desk questions
   ============================================================ */
const FAQ_CATEGORIES = [
  { id: "ordering",   en: "Ordering & quotes",   ar: "الطلب وعرض الأسعار" },
  { id: "shipping",   en: "Shipping & delivery", ar: "الشحن والتسليم" },
  { id: "specimens",  en: "Plant specimens",     ar: "النباتات والمواصفات" },
  { id: "after",      en: "After-sale support",  ar: "ما بعد البيع" },
];

const FAQS = [
  { cat: "ordering", q: { en: "What's the minimum order quantity?", ar: "ما هو الحد الأدنى للطلب؟" },
    a: { en: "MOQs are set per specimen — listed on every product page. Most ornamentals start at 50 units, palms at 25, and ground cover at 500. We can mix species within a single 40-ft container.",
         ar: "الحد الأدنى محدد لكل نبات على صفحته. أغلب نباتات الزينة تبدأ من 50 وحدة، النخيل من 25، والغطاء الأرضي من 500. يمكن خلط الأنواع داخل الحاوية الواحدة." } },
  { cat: "ordering", q: { en: "How quickly will I receive a quote?", ar: "متى أستلم عرض السعر؟" },
    a: { en: "Within one working day during business hours (Sun–Thu, 08:00–18:00 TRT). For urgent enquiries, contact our trade desk on WhatsApp — we usually reply within an hour.",
         ar: "خلال يوم عمل واحد (الأحد–الخميس، 08:00–18:00 بتوقيت تركيا). للطلبات العاجلة، تواصل معنا عبر الواتساب — نرد عادةً خلال ساعة." } },
  { cat: "ordering", q: { en: "What are your payment terms?", ar: "ما هي شروط الدفع؟" },
    a: { en: "50% deposit on order confirmation, 50% before container loading. We accept SWIFT, USD or EUR. For first orders we may request a proforma invoice and bank reference; established trade partners can apply for net-30 terms.",
         ar: "50% عند تأكيد الطلب و50% قبل تحميل الحاوية. نقبل التحويل البنكي بالدولار أو اليورو. للطلبات الجديدة قد نطلب فاتورة مبدئية ومرجعاً بنكياً، وللعملاء الدائمين يمكن التقديم لشروط دفع آجل 30 يوم." } },
  { cat: "shipping", q: { en: "Which ports do you ship to?", ar: "إلى أي موانئ تشحنون؟" },
    a: { en: "Weekly reefer / open-top departures to Jebel Ali (UAE), Dammam (KSA), Hamad Port (Qatar), Aqaba (Jordan), Alexandria (Egypt), Misrata (Libya), Beirut (Lebanon) and Latakia (Syria). Other ports possible on request.",
         ar: "شحن أسبوعي إلى جبل علي (الإمارات)، الدمام (السعودية)، ميناء حمد (قطر)، العقبة (الأردن)، الإسكندرية (مصر)، مصراتة (ليبيا)، بيروت (لبنان) واللاذقية (سوريا). موانئ أخرى متاحة حسب الطلب." } },
  { cat: "shipping", q: { en: "How long does shipping take?", ar: "كم تستغرق مدة الشحن؟" },
    a: { en: "From Yalova: 7–10 days to Gulf ports, 4–6 days to Levant ports, 10–14 days to North African ports. Add 5–14 days for in-stock preparation and 6–10 weeks for grown-to-order specimens.",
         ar: "من يالوفا: 7–10 أيام لموانئ الخليج، 4–6 أيام للشام، 10–14 يوم لشمال أفريقيا. أضف 5–14 يوم للتحضير و6–10 أسابيع للنباتات بحسب الطلب." } },
  { cat: "shipping", q: { en: "Who handles customs clearance?", ar: "من يتولى التخليص الجمركي؟" },
    a: { en: "We ship CIF by default — Bitki Hub handles export documentation, phytosanitary certificates and EU plant passports. You handle import clearance at your destination port, with our customs team's full document support.",
         ar: "نشحن بشروط CIF افتراضياً — نتولى نحن وثائق التصدير والشهادات الصحية وجواز السفر النباتي الأوروبي. أنت تتولى التخليص في ميناء الوصول مع دعم وثائقي كامل من فريقنا." } },
  { cat: "specimens", q: { en: "Are your specimens climate-adapted for the Gulf?", ar: "هل النباتات مهيأة لمناخ الخليج؟" },
    a: { en: "Every export-grade specimen has been hardened off through at least two full summer cycles in Yalova's continental climate. We specifically curate species that thrive in arid and Mediterranean conditions — palms, olives, ornamental trees and drought-tolerant ground cover.",
         ar: "كل نبات مهيأ لموسمين كاملين على الأقل في مناخ يالوفا القاري. نختار الأنواع التي تنمو جيداً في الظروف الجافة والمتوسطية — النخيل، الزيتون، أشجار الزينة، والنباتات منخفضة استهلاك المياه." } },
  { cat: "specimens", q: { en: "Do you offer custom-grown specimens?", ar: "هل تقدمون نباتات بحسب الطلب؟" },
    a: { en: "Yes. For projects requiring specific heights, trunk diameters or canopy shapes, we can grow to specification with 6–18 months lead time depending on the species. Reach out with your project brief.",
         ar: "نعم. للمشاريع التي تتطلب ارتفاعات أو أقطار جذوع أو أشكال محددة، يمكننا التربية بحسب المواصفات بمدة 6–18 شهر حسب النوع. أرسل لنا تفاصيل المشروع." } },
  { cat: "specimens", q: { en: "What certifications do your plants carry?", ar: "ما هي شهادات النباتات؟" },
    a: { en: "EU Plant Passport (every batch), Phytosanitary Certificate (issued per destination country), Global GAP, ISO 9001:2015, and full traceability tags. Documentation is sent ahead of shipment for pre-clearance.",
         ar: "جواز السفر النباتي الأوروبي لكل دفعة، شهادة صحية لكل دولة وصول، شهادة Global GAP، شهادة ISO 9001:2015، وبطاقات تتبع كاملة. ترسل الوثائق قبل الشحن للتخليص المسبق." } },
  { cat: "after", q: { en: "What is the survival guarantee?", ar: "ما هو ضمان البقاء؟" },
    a: { en: "60-day replacement guarantee on certified specimens, valid from arrival at destination port. Survival failures must be documented with photos and an agronomist's assessment; replacements ship on our next container.",
         ar: "ضمان استبدال لمدة 60 يوم للنباتات المعتمدة، يبدأ من وصول الحاوية. يتم توثيق حالات الفشل بالصور وتقرير من مهندس زراعي، وتُشحن البدائل في الحاوية التالية." } },
  { cat: "after", q: { en: "Do you provide installation support?", ar: "هل تقدمون الدعم الميداني؟" },
    a: { en: "We're a nursery, not a landscape contractor — but we work closely with our partners' agronomy teams and can connect you with vetted installation crews in most MENA capitals.",
         ar: "نحن مشتل، لا مقاول تنسيق — لكننا نعمل مع فرق الزراعة لشركائنا ويمكننا توصيلك بفرق تركيب موثوقة في معظم عواصم المنطقة." } },
];

/* ============================================================
   Blog posts — field journal
   ============================================================ */
const BLOG_CATEGORIES = [
  { id: "all",       en: "All",                ar: "الكل" },
  { id: "field",     en: "From the field",     ar: "من الحقل" },
  { id: "specimens", en: "Specimen notes",     ar: "ملاحظات نباتية" },
  { id: "trade",     en: "Trade desk",         ar: "قسم التجارة" },
  { id: "climate",   en: "Climate & care",     ar: "المناخ والعناية" },
];

const BLOG_POSTS = [
  { id: 1, cat: "field", read: 6, date: "May 12, 2026",
    title: { en: "Inside Block 4-B: how we harden 8-year-old olives for Gulf summers",
             ar: "داخل قطاع 4-B: كيف نُهيّئ زيتوناً عمره 8 سنوات لصيف الخليج" },
    excerpt: { en: "Three irrigation cycles, two transplants and one ruthless summer in Yalova — the exact protocol our flagship Olea europaea goes through before it ever sees a container.",
               ar: "ثلاث دورات ري، نقلتان، وصيف قاسٍ في يالوفا — البروتوكول الذي يمر به الزيتون الرئيسي قبل أن يصل للحاوية." },
    img: UNSPLASH("photo-1568084680786-a84f91d1153c", 1100) },
  { id: 2, cat: "trade", read: 4, date: "May 5, 2026",
    title: { en: "A landscape contractor's container math: 1,400 palms, 18 months, one boulevard",
             ar: "حسابات مقاول التنسيق: 1400 نخلة، 18 شهراً، شارع واحد" },
    excerpt: { en: "Breakdown of a Red Sea Resort installation — how to phase deliveries, when to ship in mixed loads, and the documentation that saves you a week at customs.",
               ar: "تحليل تنفيذ منتجع البحر الأحمر — كيفية تقسيم الشحنات، متى تشحن خلطات، والوثائق التي توفر أسبوعاً في الجمارك." },
    img: UNSPLASH("photo-1469474968028-56623f02e42e", 1100) },
  { id: 3, cat: "specimens", read: 8, date: "April 28, 2026",
    title: { en: "Phoenix dactylifera vs Washingtonia robusta: which palm for which boulevard",
             ar: "نخيل التمر مقابل نخيل واشنطن: أيهما يناسب الشارع" },
    excerpt: { en: "Trunk maturity, canopy spread, water budget and visual silhouette — a side-by-side decision matrix for landscape architects working in the Gulf.",
               ar: "نضج الجذع، انتشار الورقة، استهلاك الماء والشكل البصري — مصفوفة قرار جنباً إلى جنب للمهندسين." },
    img: UNSPLASH("photo-1503614472-8c93d56e92ce", 1100) },
  { id: 4, cat: "climate", read: 5, date: "April 18, 2026",
    title: { en: "What 'climate-adapted' actually means (and what it doesn't)",
             ar: "ما الذي تعنيه عبارة 'مُكيّف مناخياً' فعلاً (وما لا تعنيه)" },
    excerpt: { en: "An honest field note on why hardening off in Yalova is not the same as adapting to 48°C summers — and the post-arrival protocols that close the gap.",
               ar: "ملاحظة صريحة عن لماذا التهيئة في يالوفا لا تساوي التأقلم مع صيف 48 درجة — والإجراءات التي تسد الفجوة بعد الوصول." },
    img: UNSPLASH("photo-1416879595882-3373a0480b5b", 1100) },
  { id: 5, cat: "trade", read: 3, date: "April 9, 2026",
    title: { en: "New for 2026: weekly direct service to Hamad Port, Qatar",
             ar: "جديد 2026: خدمة أسبوعية مباشرة لميناء حمد، قطر" },
    excerpt: { en: "Cutting 5–7 days off Qatar deliveries with a dedicated reefer slot every Tuesday from Yalova port.",
               ar: "نقلص 5–7 أيام من زمن التسليم إلى قطر مع خانة شحن مخصصة كل ثلاثاء من ميناء يالوفا." },
    img: UNSPLASH("photo-1466692476868-aef1dfb1e735", 1100) },
  { id: 6, cat: "specimens", read: 7, date: "March 30, 2026",
    title: { en: "Why the fiddle-leaf still works for hotel lobbies in 2026",
             ar: "لماذا لا يزال تين الكمان مناسباً لبهو الفنادق في 2026" },
    excerpt: { en: "On longevity, glare tolerance, and the simple maintenance trick we share with our hospitality clients to keep specimens lobby-ready for years.",
               ar: "حول الديمومة، تحمّل الإضاءة، وحيلة الصيانة البسيطة التي نشاركها مع عملاء الضيافة." },
    img: UNSPLASH("photo-1485955900006-10f4d324d411", 1100) },
];

Object.assign(window, { CATEGORIES, PRODUCTS, PROJECTS, STRINGS, COUNTRIES_EN, COUNTRIES_AR, UNSPLASH, DIAL_CODES, FAQ_CATEGORIES, FAQS, BLOG_CATEGORIES, BLOG_POSTS });
